apiVersion: v1
entries:
  casdoor-helm-charts:
  - apiVersion: v2
    appVersion: v1.497.0
    created: "2024-01-11T08:25:06.782374644Z"
    description: A Helm chart for Kubernetes
    digest: 847fa0aab2d7f98f9a1b5ab6442015c8e6338f026b03bb65b121b58b325f6d9c
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.3.tgz
    version: 0.4.3
generated: "2024-01-11T08:25:06.781748264Z"
