apiVersion: v1
entries:
  casdoor-helm-charts:
  - apiVersion: v2
    appVersion: v1.508.0
    created: "2024-01-20T08:15:03.555926244Z"
    description: A Helm chart for Kubernetes
    digest: 5854e0d5a1e0cea3066f4acdabf01f05f9b390b7d92f4a6fd55da5013a23b30a
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.508.0.tgz
    version: v1.508.0
  - apiVersion: v2
    appVersion: v1.507.0
    created: "2024-01-19T14:28:21.170527579Z"
    description: A Helm chart for Kubernetes
    digest: 0f834b909782a702c981c73e3a3cfcace4faba295429323da8c1a37718605f81
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.507.0.tgz
    version: v1.507.0
  - apiVersion: v2
    appVersion: v1.506.0
    created: "2024-01-19T08:47:38.574116102Z"
    description: A Helm chart for Kubernetes
    digest: af805c8ecd9ff30cf6e363437da53355c75e6f0955e480b9af584199575cdda4
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.506.0.tgz
    version: v1.506.0
  - apiVersion: v2
    appVersion: v1.505.0
    created: "2024-01-18T13:15:10.086236752Z"
    description: A Helm chart for Kubernetes
    digest: dd987741237cbf3ecdebe4ab3197f60551ff513d4dfcde514ba1ecbc9bc03468
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.505.0.tgz
    version: v1.505.0
  - apiVersion: v2
    appVersion: v1.504.0
    created: "2024-01-17T05:23:21.009165397Z"
    description: A Helm chart for Kubernetes
    digest: 791edb91b417cd89841605d034af4de62d9f6d5e1bf9293778c2f654130fd8a5
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.504.0.tgz
    version: v1.504.0
  - apiVersion: v2
    appVersion: v1.503.0
    created: "2024-01-15T10:28:22.168684063Z"
    description: A Helm chart for Kubernetes
    digest: 7bd9beece3eae33622273306f772758a6f827cb11ecf98f097e2ff56f3fc13f0
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.503.0.tgz
    version: v1.503.0
  - apiVersion: v2
    appVersion: v1.502.0
    created: "2024-01-15T06:13:59.012071746Z"
    description: A Helm chart for Kubernetes
    digest: b1f17211650a19c611c0df1999ce1a4f5952912623d5acd6f56bf0c0eca8ed3b
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.502.0.tgz
    version: v1.502.0
  - apiVersion: v2
    appVersion: v1.501.0
    created: "2024-01-15T02:30:49.912499904Z"
    description: A Helm chart for Kubernetes
    digest: e4002420c653e401e45b5945f806e735ae01043b673e3cd8c814bb3205f808f2
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.501.0.tgz
    version: v1.501.0
  - apiVersion: v2
    appVersion: v1.499.0
    created: "2024-01-13T08:25:19.954715378Z"
    description: A Helm chart for Kubernetes
    digest: b3d72700e132c672cd7320b0d85ccbe02a13688f001581181e3b41a00feae0f8
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.5.tgz
    version: 0.4.5
  - apiVersion: v2
    appVersion: v1.498.0
    created: "2024-01-13T03:52:38.843292507Z"
    description: A Helm chart for Kubernetes
    digest: 9b136a3fbf283b45b9dead5ca189a6db48d9307378127861f527e40f51213961
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: v1.497.0
    created: "2024-01-11T08:25:06.782374644Z"
    description: A Helm chart for Kubernetes
    digest: 847fa0aab2d7f98f9a1b5ab6442015c8e6338f026b03bb65b121b58b325f6d9c
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.3.tgz
    version: 0.4.3
generated: "2024-01-20T08:15:03.548852181Z"
